services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass123
      POSTGRES_DB: school_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser -d school_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: golang:1.23-alpine
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=devuser
      - DB_PASSWORD=devpass123
      - DB_NAME=school_db
      - DB_SSL_MODE=disable
      - JWT_SECRET=your-256-bit-secret-key-here-change-in-production
      - PORT=8080
      - ENV=development
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080
    volumes:
      - .:/app
    command: sh -c "apk add --no-cache git && go run cmd/api/main.go"

volumes:
  postgres_data: